# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'derin1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import train
from yapayz import model_training ,decision
from PyQt5 import QtCore, QtGui, QtWidgets
import tkinter as tk
from tkinter import filedialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tab.setStyleSheet("background-color: #fffdd0")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(700, 190, 101, 20))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(200, 270, 70, 20))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(700, 110, 170, 20))
        self.label_6.setObjectName("label_6")
        self.epochsize = QtWidgets.QPlainTextEdit(self.tab)
        self.epochsize.setGeometry(QtCore.QRect(400, 260, 241, 41))
        self.epochsize.setObjectName("epochsize")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(200, 190, 151, 21))
        self.label_3.setObjectName("label_3")
        self.txtearlystop = QtWidgets.QPlainTextEdit(self.tab)
        self.txtearlystop.setGeometry(QtCore.QRect(900, 100, 241, 41))
        self.txtearlystop.setObjectName("txtearlystop")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(400, 40, 245, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(200, 110, 100, 20))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(200, 50, 60, 13))
        self.label.setObjectName("label")
        self.txtdabach = QtWidgets.QPlainTextEdit(self.tab)
        self.txtdabach.setGeometry(QtCore.QRect(400, 180, 241, 41))
        self.txtdabach.setObjectName("txtdabach")
        self.txttestsize = QtWidgets.QPlainTextEdit(self.tab)
        self.txttestsize.setGeometry(QtCore.QRect(400, 340, 241, 41))
        self.txttestsize.setObjectName("txttestsize")
        self.txtkfold = QtWidgets.QPlainTextEdit(self.tab)
        self.txtkfold.setGeometry(QtCore.QRect(400, 100, 241, 41))
        self.txtkfold.setObjectName("txtkfold")
        self.accloss = QtWidgets.QLabel(self.tab)
        self.accloss.setGeometry(QtCore.QRect(600, 400, 481, 351))
        self.accloss.setText("")
        self.accloss.setObjectName("accloss")
        self.txtrndstate = QtWidgets.QPlainTextEdit(self.tab)
        self.txtrndstate.setGeometry(QtCore.QRect(900, 260, 241, 41))
        self.txtrndstate.setObjectName("txtrndstate")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(200, 350, 151, 20))
        self.label_7.setObjectName("label_7")
        self.txtstepsepoch = QtWidgets.QPlainTextEdit(self.tab)
        self.txtstepsepoch.setGeometry(QtCore.QRect(900, 180, 241, 41))
        self.txtstepsepoch.setObjectName("txtstepsepoch")
        self.cm = QtWidgets.QLabel(self.tab)
        self.cm.setGeometry(QtCore.QRect(900, 400, 600, 600))
        self.cm.setText("")
        self.cm.setObjectName("cm")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(700, 270, 151, 20))
        self.label_8.setObjectName("label_8")
        self.pushButtonfit = QtWidgets.QPushButton(self.tab)
        self.pushButtonfit.setGeometry(QtCore.QRect(470, 420, 100, 30))
        self.pushButtonfit.setObjectName("pushButtonfit")
        self.pushButtonfit.clicked.connect(self.butonclick)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox2.setGeometry(QtCore.QRect(400, 40, 201, 31))
        self.comboBox2.setObjectName("comboBox2")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.comboBox2.addItem("")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(400, 60, 100, 100))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(470, 700, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.butonclick2)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1198, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        self.label_5.setText(_translate("MainWindow", "Epoch Adımları :"))
        self.label_4.setText(_translate("MainWindow", "Epoch Size : "))
        self.label_6.setText(_translate("MainWindow", "Erken durdurma toleransı : "))
        self.label_3.setText(_translate("MainWindow", "Batch Size : "))
        self.comboBox.setItemText(0, _translate("MainWindow", "Kendi CNN Modelim"))
        self.comboBox.setItemText(1, _translate("MainWindow", "VGG16 CNN Modeli"))
        self.comboBox.setItemText(2, _translate("MainWindow", "VGG19 CNN Modeli"))
        self.comboBox2.setItemText(0, _translate("MainWindow", "mycnn"))
        self.comboBox2.setItemText(1, _translate("MainWindow", "vgg16"))
        self.comboBox2.setItemText(2, _translate("MainWindow", "vgg19"))
        self.cm.setPixmap(QtGui.QPixmap("./x.jpg"))
        self.label_2.setText(_translate("MainWindow", "K-Fold Değeri :"))
        self.label.setText(_translate("MainWindow", "Algoritma Seçin :"))
        self.label_7.setText(_translate("MainWindow", "Test Size :"))
        self.label_8.setText(_translate("MainWindow", "Random-State Değeri :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.pushButton.setText(_translate("MainWindow", "modele veri gir "))
        self.pushButtonfit.setText(_translate("MainWindow", "Eğitimi Başlat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
    def butonclick(self, event):
        index = self.comboBox.currentIndex()
        kf = int(self.txtkfold.toPlainText())
        dabch = int(self.txtdabach.toPlainText())
        epoch = int(self.epochsize.toPlainText())
        stepepoch = int(self.txtstepsepoch.toPlainText())
        earlystop = int(self.txtearlystop.toPlainText())
        test_size = int(self.txttestsize.toPlainText())
        rndstate = int(self.txtrndstate.toPlainText())
        if index == 0 :
            model_training.main(epoch,dabch)
            self.cm.setPixmap(QtGui.QPixmap("./_confusion_matrix.png"))
        elif index > 0 :
            train.train(kf,dabch,epoch,stepepoch,earlystop,test_size,rndstate,index)
            self.cm.setPixmap(QtGui.QPixmap("./_confusion_matrix.png"))
            
    def butonclick2(self, event):
        file_path = filedialog.askopenfilename(initialdir="./", title="select files",
                                               filetypes=(("jpg files", "*.jpg"), ("png files", "*.png")))
        index = self.comboBox.currentIndex()
        if index == 0 :
            a=decision.isfire(file_path,"C:/Users/Monster/Desktop/Yeni klasör/yapayz/models/model_myCNN.h5")
            self.label_10.setText(a)
        elif index > 0 :
            a = decision.isfire(file_path,"C:/Users/Monster/Desktop/Yeni klasör/checkpoint/eyesDetectionCheckpoint.h5")
            self.label_10.setText(a)
            

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
